using PickDuel.Domain.Entities;

namespace PickDuel.Application.Repositories.Interfaces;

public interface IScoreEventRepository
{
    /// <summary>
    /// Adds a new score event to the data store.
    /// </summary>
    /// <param name="scoreEvent">Score event entity to add.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task AddAsync(ScoreEvent scoreEvent, CancellationToken cancellationToken = default);


    /// <summary>
    /// Retrieves a score event by identifier.
    /// </summary>
    /// <param name="scoreEventId">Score event identifier.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The score event if found; otherwise null.</returns>
    Task<ScoreEvent?> GetByIdAsync(Guid scoreEventId, CancellationToken cancellationToken = default);


    /// <summary>
    /// Retrieves score events for a user.
    /// </summary>
    /// <param name="userId">User identifier.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>User score events.</returns>
    Task<IReadOnlyCollection<ScoreEvent>> GetByUserIdAsync(Guid userId, CancellationToken cancellationToken = default);


    /// <summary>
    /// Retrieves score events for a league.
    /// </summary>
    /// <param name="leagueId">League identifier.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>League score events.</returns>
    Task<IReadOnlyCollection<ScoreEvent>> GetByLeagueIdAsync(Guid leagueId, CancellationToken cancellationToken = default);


    /// <summary>
    /// Retrieves score events generated by a pick.
    /// </summary>
    /// <param name="pickId">Pick identifier.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Matching score events.</returns>
    Task<IReadOnlyCollection<ScoreEvent>> GetByPickIdAsync(Guid pickId, CancellationToken cancellationToken = default);


    /// <summary>
    /// Removes a score event.
    /// </summary>
    /// <param name="scoreEvent">Score event entity to remove.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task DeleteAsync(ScoreEvent scoreEvent, CancellationToken cancellationToken = default);


    /// <summary>
    /// Saves all pending repository changes.
    /// </summary>
    /// <param name="cancellationToken">Cancellation token.</param>
    Task SaveChangesAsync(CancellationToken cancellationToken = default);
}